---
title: "Introduction to Classification and Clustering"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
bibliography: Multivariate.bib
csl: evolution.csl
---


```{r}
#| label: setup
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(cowplot)

ggplot2::theme_set(theme_cowplot())
```


## DFA / LDA

Linear separation of groups


## Simulate data: 2 Groups

```{r}
library(mvtnorm)

set.seed(347977)
n <- 100

sigma <- rbind(c(1.0, 0.3),
               c(0.3, 1.0))
G1 <- rmvnorm(n = n, mean = c(-2, -2), sigma = sigma)
G2 <- rmvnorm(n = n, mean = c(0, 2), sigma = sigma)
G <- data.frame(rbind(G1, G2))

SD2 <- data.frame(Group = factor(rep(LETTERS[1:2], each = n)),
                 G)

ggplot(SD2, aes(X1, X2, color = Group)) +
  geom_point(size = 3) +
  coord_equal() +
  scale_color_brewer(type = "qual", palette = "Set1")
```


## Simulate data: 3  Groups

```{r}
set.seed(347977)
n <- 100

sigma <- rbind(c(1.0, 0.3),
               c(0.3, 1.0))
G1 <- rmvnorm(n = n, mean = c(-2, -2), sigma = sigma)
G2 <- rmvnorm(n = n, mean = c(0, 2), sigma = sigma)
G3 <- rmvnorm(n = n, mean = c(2, -1), sigma = sigma)
G <- data.frame(rbind(G1, G2, G3))

SD3 <- data.frame(Group = factor(rep(LETTERS[1:3], each = n)),
                 G)

ggplot(SD3, aes(X1, X2, color = Group)) +
  geom_point(size = 3) +
  coord_equal() +
  scale_color_brewer(type = "qual", palette = "Set1")

write_rds(SD2, file = "Data/SD2.rds")
write_rds(SD3, file = "Data/SD3.rds")
```




## References

::: {#refs}
:::

