---
title: "Classification and Regression Trees"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
bibliography: Multivariate.bib
csl: evolution.csl
---


```{r}
#| label: setup
#| echo: false
#| warning: false
#| message: false

library(tidyverse)
library(cowplot)
library(rsample)
library(mvtnorm)

ggplot2::theme_set(theme_cowplot())

SD2 <- read_rds("Data/SD2.rds")
SD3 <- read_rds("Data/SD3.rds")
```

## CRAN Taskview

[Machine Learning](https://cran.r-project.org/web/views/MachineLearning.html)


## CART intro

```{r}
library(rpart)
library(rpart.plot)

tree <- rpart(Group ~ X1 + X2, data = SD3,
              control = rpart.control(cp=.0001))

#view results
printcp(tree)

#identify best cp value to use
best <- tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"]

#produce a pruned tree based on the best cp value
pruned_tree <- prune(tree, cp=best)

#plot the pruned tree
prp(pruned_tree,
    faclen = 0, #use full names for factor labels
    extra = 1, #display number of obs. for each terminal node
    roundint = F, #don't round to integers in output
    digits = 5) #display 5 decimal places in output

draw.tree (pruned_tree,
           nodeinfo=TRUE, units="species", cases="cells", digits=0)
```



## References

::: {#refs}
:::

