---
title: "Final Project"
author:
  - Your Name Here
format: 
  html:
    embed-resources: true
---

## Instructions

For the final project for Multivariate Methods, you will have 2 options described below. Choose one option - do not do both! We will take some time to discuss possible datasets with each of you during our week 3 check in meeting. 


#### Option A

Identify a paper from the primary literature that has a dataset that has been or could be analyzed using one of the methods we've covered in this module. Perform the analysis in R, either reproducing what the paper has done or analyzing the dataset in a new way if you think that is appropriate and useful. Write a short description summarizing the dataset and how it was collected and the analysis methods and results you have found. Especially highlight any differences in your analysis compared to the original publication. The entire thing should be written in this `.qmd` file, formatting the analysis, plots, etc. 

Things to include:

- The citation of the paper that the dataset is from
- The hypotheses to be tested
- The major methods employed
- Your main results 
- Relevant figures    


#### Option B

Analyze your own dataset and write the methods and results sections as you would for a manuscript. Ideally, you would use a dataset you are working on analyzing and intending to publish but you can use any dataset you have if you don't have one like that right now. If you've done a similar analysis for another module in QMLS2, you can use that same dataset here.

Your data and analysis doesn't have to be overly complicated, and if your actual data would demand a more complex model than we have used (e.g., multilevel or non-linear), feel free to simplify the data for the purposes of analysis.

You should restrict your writing to the methods about the analysis you have done. You do not need to include the other parts of the methods describing the experiment, etc. Just include enough to know what questions you are answering and/or what hypotheses you are testing. The same is true for your results section. Simply write the sections describing the results of the analyses you do here. The entire thing should be written in this `.qmd` file, formatting the analysis, plots, etc. 

Things to include:

- The hypotheses to be tested
- The major methods employed
- Your main results 
- Relevant figures
    - Although you might not include all these figures in a manuscript, they could very easily go into supplemental information.

